from typing import Any

total_points: list[float] = [
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    5.0,
    5.0,
]

solutions: dict[str, Any] = {
    "q1-1-calculate-standard-deviation": "The standard deviation of the array is 5.938",
    "q1-2-what-datatype-has-the-highest-precision": "np.float64",
    "q1-3-understanding-classes": "It initializes a new object when the class is called",
    "q1-4-control-structures-in-python": "end",
    "q1-5-True-statement": "True",
    "q1-6-ethical-plotting-in-python": "Labeling axes clearly and choosing colorblind-friendly palettes",
    "q1-7-machine-learning-overfitting": "Overfitting can be mitigated by techniques such as regularization, cross-validation, or increasing training data.",
    "q1-8-intro-to-magic-methods": "They are automatically called by Python for certain operations.",
    "q1-9-variable-scope-basics": "They are unique to each object created from the class.",
    "q2-1-python-objects": [
        "Integer",
        "String",
        "Decorator",
        "Bytes",
        "Module",
        "Class",
        "Exception",
    ],
    "q2-2-python-data-structures": ["List", "Dictionary", "Tuple"],
    "q2-4-python-dictionaries": [
        "Another dictionary",
        "A custom class instance",
        "A lambda function",
        "A built-in function like `len`",
        "A module object",
    ],
    "q2-5-python-mutability": ["List", "Dictionary", "Class instance"],
    "q2-6-floating-point-numbers": [
        "They can cause precision issues due to binary representation.",
        "They are immutable.",
        "They can be used as dictionary keys.",
    ],
    "q2-7-python-classes": [
        "They can define both instance methods and class methods.",
        "They can utilize decorators like `@classmethod` and `@staticmethod`.",
        "They are defined using the `class` keyword.",
    ],
    "q2-8-continue-break-else": ["`break`", "`continue`", "`for`", "`else`"],
    "q2-9-python-inheritance-basics": [
        "A child class can use methods from its parent class.",
        "Inheritance helps avoid repeating code.",
    ],
    "q2-10-valid-python-syntax": [
        "for i in range(5):",
        "if x > 0:",
        "def my_function(param):",
        "while True:",
        "class MyClass:",
        "import os",
    ],
    "q2-11-machine-learning-basics": [
        "Machine learning models learn from data.",
        "More data can help improve model performance.",
        "Some models work better on certain types of data.",
        "Most machine learning models are biased in some way.",
    ],
    "q5-1-Model-Improvements": [
        "The model might be improved by adding more training data",
        "The model might be improved using data augmentation to manipulate the training data",
        "The model is sufficient to be practically useful for this task",
    ],
    "q5-2-Model-Performance": [
        "The model is very accurate at predicting handwritten digits on the training dataset",
        "The model is very accurate at predicting handwritten digits on the test dataset",
        "The model is useful for predicting handwritten digits",
        "The model is a supervised model",
    ],
}
