[project]
name = "engr-131-api"
version = "0.1.0"
description = "TBD"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "alembic>=1.13.2",
  "bcrypt>=4.2.0",
  "fastapi[standard]>=0.115.0",
  "mypy>=1.13.0",
  "psycopg2-binary>=2.9.9",
  "pykubegrader>=0.2.25",
  "pynacl>=1.5.0",
  "ruff>=0.6.7",
  "pytz",
]

[tool.mypy]
exclude = ["vendor"]

[tool.ruff]
exclude = ["vendor"]

[tool.pyright]
venvPath = "."
venv = ".venv"
