[project]
name = "engr-131-api"
version = "0.1.0"
description = "TBD"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "alembic>=1.14.0",
  "bcrypt>=4.2.1",
  "fastapi[standard]>=0.115.6",
  "numpy>=2.2.1",
  "psycopg2-binary>=2.9.10",
  "pynacl>=1.5.0",
]

[dependency-groups]
dev = ["mypy>=1.14.1", "ruff>=0.9.2", "types-python-dateutil>=2.9.0.20241206"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.mypy]
exclude = ["vendor"]

[tool.ruff]
exclude = ["vendor"]

[tool.pyright]
venvPath = "."
venv = ".venv"
