"""Submission

Revision ID: 01e014984cf4
Revises: 00df6c33fe4d
Create Date: 2024-12-22 10:00:05.174340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01e014984cf4"
down_revision: Union[str, None] = "00df6c33fe4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions", sa.Column("raw_score", sa.Integer(), nullable=False)
    )
    op.add_column(
        "assignment_submissions",
        sa.Column("late_assignment_percentage", sa.Integer(), nullable=False),
    )
    op.add_column(
        "assignment_submissions", sa.Column("final_score", sa.Integer(), nullable=False)
    )
    op.drop_column("assignment_submissions", "score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("assignment_submissions", "final_score")
    op.drop_column("assignment_submissions", "late_assignment_percentage")
    op.drop_column("assignment_submissions", "raw_score")
    # ### end Alembic commands ###
