"""add question schema

Revision ID: 0aa52946ec1d
Revises: 3ee2bbc1299b
Create Date: 2025-02-02 11:52:24.770597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0aa52946ec1d"
down_revision: Union[str, None] = "3ee2bbc1299b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("max_points", sa.Float(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("assignment_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment"],
            ["assignments.title"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
