"""Make student name fields optional

Revision ID: 24f3788928df
Revises: 01e014984cf4
Create Date: 2024-12-23 12:57:47.589414

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24f3788928df"
down_revision: Union[str, None] = "01e014984cf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "family_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("students", "given_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "given_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "students", "family_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
