"""Do some stuff

Revision ID: 2dbb284ed385
Revises: 51f9677469cb
Create Date: 2025-03-11 12:03:02.966048

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dbb284ed385"
down_revision: Union[str, None] = "51f9677469cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students_completed_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("assignment_type", sa.String(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("student_seed", sa.Integer(), nullable=False),
        sa.Column("key_used", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_students_completed_assignments_assignment"),
        "students_completed_assignments",
        ["assignment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_students_completed_assignments_student_email"),
        "students_completed_assignments",
        ["student_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_students_completed_assignments_student_email"),
        table_name="students_completed_assignments",
    )
    op.drop_index(
        op.f("ix_students_completed_assignments_assignment"),
        table_name="students_completed_assignments",
    )
    op.drop_table("students_completed_assignments")
    # ### end Alembic commands ###
