"""Submission schema

Revision ID: 38b7c1cafba9
Revises: 8545478cfc11
Create Date: 2025-01-03 16:57:20.994013

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38b7c1cafba9"
down_revision: Union[str, None] = "8545478cfc11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column("student_email", sa.String(), nullable=False),
    )
    op.drop_constraint(
        "assignment_submissions_assignment_fkey",
        "assignment_submissions",
        type_="foreignkey",
    )
    op.drop_column("assignment_submissions", "students.email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column("students.email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "assignment_submissions_assignment_fkey",
        "assignment_submissions",
        "assignments",
        ["assignment"],
        ["title"],
    )
    op.drop_column("assignment_submissions", "student_email")
    # ### end Alembic commands ###
