"""Add execution logs table

Revision ID: 3ee2bbc1299b
Revises: 71de2dbb22ba
Create Date: 2025-01-27 16:47:01.718581

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ee2bbc1299b"
down_revision: Union[str, None] = "71de2dbb22ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "upload_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("encrypted_content", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_logs_assignment"),
        "execution_logs",
        ["assignment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_logs_student_email"),
        "execution_logs",
        ["student_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_logs_student_email"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_assignment"), table_name="execution_logs")
    op.drop_table("execution_logs")
    # ### end Alembic commands ###
