"""Submission schema

Revision ID: 440de3e60308
Revises: a0ab6b9b0eb3
Create Date: 2025-01-03 13:30:00.676636

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "440de3e60308"
down_revision: Union[str, None] = "a0ab6b9b0eb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
