"""Add question submission table

Revision ID: 501abed1abc0
Revises: bceb6537b636
Create Date: 2024-11-21 11:08:13.265394

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "501abed1abc0"
down_revision: Union[str, None] = "bceb6537b636"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("max_points", sa.Integer(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment"],
            ["assignments.title"],
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["students.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_submissions")
    # ### end Alembic commands ###
