"""Update questions table schema

Revision ID: 564a8417314e
Revises: e0d9bd285ec6
Create Date: 2025-02-06 17:26:50.327687

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "564a8417314e"
down_revision: Union[str, None] = "e0d9bd285ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "questions", "assignment", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_index(
        op.f("ix_questions_assignment"), "questions", ["assignment"], unique=False
    )
    op.create_index(op.f("ix_questions_title"), "questions", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_title"), table_name="questions")
    op.drop_index(op.f("ix_questions_assignment"), table_name="questions")
    op.alter_column(
        "questions", "assignment", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("questions", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
