"""update token

Revision ID: 60acf6f75662
Revises: a91e72f619d0
Create Date: 2025-02-08 20:24:59.152903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60acf6f75662"
down_revision: Union[str, None] = "a91e72f619d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("student_id", sa.String(), nullable=True))
    op.add_column("tokens", sa.Column("assignment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "assignment")
    op.drop_column("tokens", "student_id")
    # ### end Alembic commands ###
