"""Submission schema

Revision ID: 60bcb152299a
Revises: 440de3e60308
Create Date: 2025-01-03 16:31:00.789889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60bcb152299a"
down_revision: Union[str, None] = "440de3e60308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions", sa.Column("week_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "assignment_submissions",
        sa.Column("assignment_type", sa.String(), nullable=True),
    )
    op.add_column(
        "assignment_submissions",
        sa.Column("student_seed", sa.Integer(), nullable=False),
    )
    op.add_column(
        "assignment_submissions", sa.Column("due_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "assignment_submissions",
        sa.Column("submitted_score", sa.Float(), nullable=False),
    )
    op.add_column(
        "assignment_submissions",
        sa.Column("current_max_score", sa.Float(), nullable=False),
    )
    op.drop_column("assignment_submissions", "final_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column(
            "final_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("assignment_submissions", "current_max_score")
    op.drop_column("assignment_submissions", "submitted_score")
    op.drop_column("assignment_submissions", "due_date")
    op.drop_column("assignment_submissions", "student_seed")
    op.drop_column("assignment_submissions", "assignment_type")
    op.drop_column("assignment_submissions", "week_number")
    # ### end Alembic commands ###
