"""Add column for updated grades

Revision ID: 71de2dbb22ba
Revises: d4a03ada2bff
Create Date: 2025-01-17 17:48:03.019036

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71de2dbb22ba"
down_revision: Union[str, None] = "d4a03ada2bff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions", sa.Column("updated_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment_submissions", "updated_score")
    # ### end Alembic commands ###
