"""token revision

Revision ID: 7c90ba8de7c7
Revises: 4c8b093174a9
Create Date: 2025-01-05 20:53:30.460053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c90ba8de7c7'
down_revision: Union[str, None] = '4c8b093174a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('requester', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'requester')
    # ### end Alembic commands ###
