"""Submission schema

Revision ID: 8545478cfc11
Revises: 60bcb152299a
Create Date: 2025-01-03 16:34:22.959422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8545478cfc11'
down_revision: Union[str, None] = '60bcb152299a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('students.email', sa.String(), nullable=False))
    op.drop_constraint('assignment_submissions_student_email_fkey', 'assignment_submissions', type_='foreignkey')
    op.drop_column('assignment_submissions', 'student_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('student_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('assignment_submissions_student_email_fkey', 'assignment_submissions', 'students', ['student_email'], ['email'])
    op.drop_column('assignment_submissions', 'students.email')
    # ### end Alembic commands ###
