"""notebook schema

Revision ID: 94244c719ab1
Revises: 38b7c1cafba9
Create Date: 2025-01-04 20:38:09.818148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94244c719ab1'
down_revision: Union[str, None] = '38b7c1cafba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebooks_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.Column('notebook', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('student_seed', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('late_assignment_percentage', sa.Float(), nullable=False),
    sa.Column('submitted_score', sa.Float(), nullable=False),
    sa.Column('current_max_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebooks_submissions')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
