"""Submission

Revision ID: a0ab6b9b0eb3
Revises: 32c4fd5099e0
Create Date: 2025-01-03 13:09:58.804710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0ab6b9b0eb3"
down_revision: Union[str, None] = "32c4fd5099e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignments", sa.Column("week_number", sa.Integer(), nullable=True))
    op.add_column(
        "assignments", sa.Column("assignment_type", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "assignment_type")
    op.drop_column("assignments", "week_number")
    # ### end Alembic commands ###
