"""Add due date extensions table

Revision ID: a91e72f619d0
Revises: 564a8417314e
Create Date: 2025-02-07 04:43:04.158671

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a91e72f619d0"
down_revision: Union[str, None] = "564a8417314e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "due_date_extensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("new_due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("orig_due_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_due_date_extensions_assignment"),
        "due_date_extensions",
        ["assignment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_due_date_extensions_student_email"),
        "due_date_extensions",
        ["student_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_due_date_extensions_student_email"), table_name="due_date_extensions"
    )
    op.drop_index(
        op.f("ix_due_date_extensions_assignment"), table_name="due_date_extensions"
    )
    op.drop_table("due_date_extensions")
    # ### end Alembic commands ###
