"""Miscellaneous schema updates

Revision ID: bceb6537b636
Revises: e198c2ee69c6
Create Date: 2024-10-28 15:52:36.092556

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bceb6537b636"
down_revision: Union[str, None] = "e198c2ee69c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("assignment", sa.String(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("max_points", sa.Integer(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment"],
            ["assignments.title"],
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["students.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("exam_submissions")
    op.drop_index("ix_exams_title", table_name="exams")
    op.drop_table("exams")
    op.add_column(
        "assignment_submissions", sa.Column("assignment", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "assignment_submissions_assignment_id_fkey",
        "assignment_submissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "assignment_submissions", "assignments", ["assignment"], ["title"]
    )
    op.drop_column("assignment_submissions", "assignment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column("assignment_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "assignment_submissions", type_="foreignkey")
    op.create_foreign_key(
        "assignment_submissions_assignment_id_fkey",
        "assignment_submissions",
        "assignments",
        ["assignment_id"],
        ["id"],
    )
    op.drop_column("assignment_submissions", "assignment")
    op.create_table(
        "exams",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('exams_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("max_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "due_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="exams_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_exams_title", "exams", ["title"], unique=True)
    op.create_table(
        "exam_submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("student_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("exam_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name="exam_submissions_exam_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["students.email"],
            name="exam_submissions_student_email_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="exam_submissions_pkey"),
    )
    op.drop_table("scoring_submissions")
    # ### end Alembic commands ###
