"""Edit table name

Revision ID: c7e1653d9db9
Revises: 7c90ba8de7c7
Create Date: 2025-01-07 09:55:56.142403

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7e1653d9db9"
down_revision: Union[str, None] = "7c90ba8de7c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("assignment_type", sa.String(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("notebook")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebook",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("week_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("assignment_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "due_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "max_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="notebook_pkey"),
    )
    op.drop_table("notebooks")
    # ### end Alembic commands ###
