"""notebook schema

Revision ID: cf1d57285cb1
Revises: 94244c719ab1
Create Date: 2025-01-04 21:02:26.379812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf1d57285cb1"
down_revision: Union[str, None] = "94244c719ab1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("assignment_type", sa.String(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notebook_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(), nullable=False),
        sa.Column("notebook", sa.String(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("assignment_type", sa.String(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("student_seed", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("late_assignment_percentage", sa.Float(), nullable=False),
        sa.Column("submitted_score", sa.Float(), nullable=False),
        sa.Column("current_max_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("notebooks_submissions")
    op.drop_table("notebooks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebooks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("week_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("assignment_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "due_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "max_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="notebooks_pkey"),
    )
    op.create_table(
        "notebooks_submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("student_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("notebook", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("week_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("assignment_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("student_seed", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "due_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "raw_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "late_assignment_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "submitted_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "current_max_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="notebooks_submissions_pkey"),
    )
    op.drop_table("notebook_submissions")
    op.drop_table("notebook")
    # ### end Alembic commands ###
