"""Add a couple indices

Revision ID: d4a03ada2bff
Revises: 301299aee630
Create Date: 2025-01-17 06:59:14.959766

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4a03ada2bff"
down_revision: Union[str, None] = "301299aee630"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_assignment_submissions_assignment"),
        "assignment_submissions",
        ["assignment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submissions_student_email"),
        "assignment_submissions",
        ["student_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assignment_submissions_student_email"),
        table_name="assignment_submissions",
    )
    op.drop_index(
        op.f("ix_assignment_submissions_assignment"),
        table_name="assignment_submissions",
    )
    # ### end Alembic commands ###
