"""add question schema

Revision ID: e0d9bd285ec6
Revises: 0aa52946ec1d
Create Date: 2025-02-02 12:08:05.058410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0d9bd285ec6"
down_revision: Union[str, None] = "0aa52946ec1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "questions", "assignment", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "questions",
        "max_points",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "questions", "due_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_constraint("questions_assignment_fkey", "questions", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "questions_assignment_fkey",
        "questions",
        "assignments",
        ["assignment"],
        ["title"],
    )
    op.alter_column(
        "questions", "due_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "questions",
        "max_points",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "questions", "assignment", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("questions", "title", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
