from typing import Any

total_points: list[float] = [
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.5,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
    3.0,
]

solutions: dict[str, Any] = {
    "q1-1-python-function-return": "`None`",
    "q1-2-formal-syntax": "It is governed by strict syntactic and grammatical rules.",
    "q1-3-python-mutability-check": "`list`",
    "q1-4-valid-identifier": "`data_point`",
    "q1-5-multiplication-operator": "`*`",
    "q1-6-volatile-memory": "RAM",
    "q1-7-numeric-datatypes": "`int`",
    "q1-8-python-commenting": "Using the `#` symbol.",
    "q1-9-list-method": "`pop()`",
    "q1-10-conditional-execution": "`Equal or Greater`",
    "q3-1-python-modules-content": "True",
    "q3-2-python-dynamic-typing": "False",
    "q3-3-python-floor-division": "True",
    "q3-4-gpu-performance": "True",
    "q3-5-list-structure": "False",
    "q3-6-python-kwargs": "False",
    "q3-7-dictionary-mutability": "True",
    "q3-8-logical-or": "True",
    "q3-9-python-data-type-count": "False",
    "q3-10-python-license": "True",
    "q2-1-programming-strategies": [
        "Breaking the problem into smaller parts.",
        "Writing pseudocode to outline a solution before coding.",
        "Debugging systematically.",
    ],
    "q2-2-python-modules": [
        "A module is a single Python file containing functions, variable, and/or classes.",
        "Modules can be imported using the `import` statement.",
        "Users can create their own modules.",
    ],
    "q2-3-python-built-in-types": ["Boolean", "Tuple"],
    "q2-4-valid-python-statements": [
        "`a = 5 + 3`",
        '`print("Hello, World!")`',
        "`_a = 5`",
    ],
    "q2-5-python-mutable-types": ["List", "Dictionary"],
    "q2-6-python-list-properties": [
        "Lists can contain elements of different data types.",
        "Lists can be resized dynamically.",
    ],
    "q2-7-floating-point-behavior": [
        "Floating-point numbers can represent decimals.",
        "Their precision is limited due to binary representation.",
        "They are immutable.",
    ],
    "q2-8-logical-operators": ["`and`", "`or`", "`not`"],
    "q2-9-python-entities": [
        "Numpy array",
        "Function",
        "Integers",
        "Float",
        "Dictionary",
        "Modules",
    ],
    "q2-10-loop-keywords": ["`break`", "`continue`"],
}
