from typing import Any

total_points: list[float] = [
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
    2.0,
]

solutions: dict[str, Any] = {
    "q1-1-program-definition": "A set of instructions that a computer executes to perform a task.",
    "q1-2-formal-vs-natural-languages": "Formal languages have strict syntax rules, while natural languages are flexible.",
    "q1-3-python-modules": "A file containing Python code that can be reused in other programs.",
    "q1-4-python-variables": "`x = 10`",
    "q1-5-python-operators": "Performs integer division.",
    "q1-6-computer-components": "Python Interpreter",
    "q1-7-python-datatypes": "List",
    "q1-8-python-comments": "`# This is a comment`",
    "q1-9-python-lists": "`[1, 2, 3, 4]`",
    "q1-10-python-mutability": "Their values can be changed after creation.",
    "q1-11-floating-point-precision": "`0.30000000000000004`",
    "q1-12-string-methods": "Removes leading and trailing whitespace from a string.",
    "q1-13-debugging-code": "`Error`",
    "q1-14-numpy-sympy": "To perform numerical computations on arrays and matrices.",
    "q1-15-boolean-operators": "`False`",
    "q1-16-control-structures": "Executes a block of code if a condition is true.",
    "q1-17-continue-break-else": "Exits the loop immediately.",
    "q3-1-program-definition": "True",
    "q3-2-formal-languages": "False",
    "q3-3-python-modules": "False",
    "q3-4-python-variables": "False",
    "q3-5-python-operators": "False",
    "q3-6-computer-components": "True",
    "q3-7-python-datatypes": "False",
    "q3-8-python-comments": "False",
    "q3-9-python-lists": "True",
    "q3-10-python-mutability": "False",
    "q3-11-floating-point-numbers": "False",
    "q3-12-string-methods": "False",
    "q3-13-debugging-code": "True",
    "q3-14-numpy-sympy": "False",
    "q3-15-boolean-operators": "True",
    "q3-16-control-structures": "True",
    "q3-17-continue-break-else": "True",
    "q2-1-programatic-thinking": [
        "Breaking down problems into smaller, manageable parts.",
        "Using algorithms to solve problems.",
    ],
    "q2-2-python-packages": [
        "A package is a collection of modules.",
        "Packages can be installed using `pip`.",
    ],
    "q2-3-python-data-types": ["Integer", "String", "List", "Dictionary"],
    "q2-4-python-expressions": ["`x + y`", "`x = 10`", '`print("Hello")`'],
    "q2-5-computer-components": ["RAM", "Hard Drive"],
    "q2-6-python-comments": ["`# This is a comment`", '`"""This is a comment"""`'],
    "q2-7-python-lists": [
        "Lists are mutable.",
        "Lists can contain elements of different data types.",
    ],
    "q2-8-python-dictionaries": [
        "Dictionaries store key-value pairs.",
        "Dictionary keys must be unique.",
        "Dictionaries are ordered modern Python versions.",
    ],
    "q2-9-python-mutability": ["List", "Dictionary"],
    "q2-10-floating-point-numbers": [
        "Floating-point numbers can represent decimal values.",
        "Floating-point numbers have limited precision.",
        "Floating-point numbers are immutable.",
    ],
    "q2-11-string-methods": ["`strip()`", "`split()`", "`replace()`"],
    "q2-12-numpy-sympy": [
        "NumPy is used for numerical computations.",
        "SymPy is used for symbolic mathematics.",
        "SymPy can perform numerical integration.",
    ],
    "q2-13-boolean-operators": ["`and`", "`or`", "`not`"],
    "q2-14-control-structures": ["`if`", "`while`", "`for`"],
    "q2-15-continue-break-else": ["`break`", "`continue`", "`else`"],
}
