name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |
          docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Buildx
        run: docker buildx inspect --bootstrap || docker buildx create --use

      - name: Build and Push Multi-Platform Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --ulimit nofile=2048:2048 \
            --tag katomyomachia/engr-131-testing:$(date +%s) \
            --push .
