name: Update Submodule & Fetch Solutions

on:
  schedule:
    - cron: "20 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update submodule to latest
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
          git status

      - name: Set up venv; run script; format files
        run: |
          export PATH=$PATH:~/.local/bin:~/.cargo/bin
          uv venv
          source .venv/bin/activate
          uv sync
          python move_solutions.py
          fd -e py . 'app/solutions/winter_2025' \
          -x sd 'total_points: float' 'total_points: list[float]'
          ruff format

      - name: Commit and push any changes
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update submodule and move solution files"
            git push
          else
            echo "No changes to commit"
          fi
