name: Update Submodule & Fetch Solutions

on:
  schedule:
    - cron: "20 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          submodules: recursive

      - name: Update submodule to latest
        run: |
          git submodule update --init --recursive
          git submodule foreach git fetch --all
          git submodule foreach 'git checkout main || true'
          git submodule update --remote --recursive
          git status

      - name: Set up venv; run script; format files
        run: |
          export PATH=$PATH:~/.local/bin:~/.cargo/bin
          uv venv
          source .venv/bin/activate
          uv sync
          python move_solutions.py
          fd -e py . 'app/solutions/winter_2025' \
          -x sd 'total_points: float' 'total_points: list[float]'
          ruff format

      - name: Commit and push changes
        run: |
          git add .
          if [ -n "$(git submodule status | grep -E '^[-+]|^ [^-]')" ]; then
            git commit -m "Update submodule to latest"
          fi
          if ! git diff-index --quiet HEAD; then
            git commit -m "Move solution files and update submodule"
            git push
          else
            echo "No changes to commit"
          fi
