name: Update PyKubeGrader dependency

on:
  schedule:
    - cron: "40 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update submodule to latest
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
          git status

      - name: Set up venv; fetch version; update
        run: |
          export PATH=$PATH:~/.local/bin
          uv venv
          source .venv/bin/activate
          PK_VER=$(curl -s "https://pypi.org/pypi/PyKubeGrader/json" | jq -r '.info.version')
          if [ -n "$PK_VER" ]; then
            echo "Fetched PyKubeGrader version: $PK_VER"
            uv add "pykubegrader>=$PK_VER"
            uv sync
            echo "PK_VER=$PK_VER" >> $GITHUB_ENV
          else
            echo "Failed to fetch version from PyPI"
            exit 1
          fi

      - name: Commit and push any changes
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update PyKubeGrader to ver. >=$PK_VER"
            git push
          else
            echo "PyKubeGrader already at version >=$PK_VER"
            echo "No changes to commit"
          fi
